### ISSUE TITLE
Not Working Properly With Recyclerview's GridLayoutManager in RTL Scenario

### ISSUE THREAD

**Issue by prabhakarkalbhile** [matrixdevz/FlyToCartAnimation#5]
I used Recyclerview with GridLayoutManager of span=2. Its working fine in LTR (Left to Right Localization).
But when I'm changes it to RTL(Right to left Localization) then, Starting Position of fly animation is only end of the screen not the clicked position of the recyclerview item. Please give me solution for that.

I hope you understand what I'm saying
Thank You For Your Time

**Comment by iabdelgawaad** [comment]
Hello @prabhakarkalbhile I face the same prob with RTL .
Do you have any solution? 

I appreciate your help,
Thanks

**Comment by matrixdevz** [comment]
@prabhakarkalbhile i will look int this and let you know what is the issue

**Comment by iabdelgawaad** [comment]
@matrixdevz Could you check this answer maybe help us to find any solution? 
https://stackoverflow.com/a/45834727/1312796

**Comment by prabhakarkalbhile** [comment]
@iabdelgawaad I didn't fond any solution yet.

**Comment by iabdelgawaad** [comment]
@prabhakarkalbhile @matrixdevz I've just solved this issue and it works perfectly in two directions. 

Just check if you are RTL or LTR inside "CircleAnimationUtil" class then change "params.setMargins" line to be like this: 

`  if (LanguageUtils.isAppLanguageArabic()) 
{
                params.setMargins(0, src[1], (getScreenWidth() - mTarget.getWidth()) - src[0], 0);
 } else
 {
                params.setMargins(src[0], src[1], 0, 0);
   }`

Add this method to get full screen width
` public int getScreenWidth() 
{
        return Resources.getSystem().getDisplayMetrics().widthPixels;
    }`

**Comment by matrixdevz** [comment]
@prabhakarkalbhile  , @iabdelgawaad  i have just pushed to master with fixes, now you can enjoy RTL support.

I have just added resources and layout changes in activity_main.xml

like marginRight > marginEnd     

This is good to start with adding  RTL support : 
https://android.jlelse.eu/rtl-support-on-android-here-is-all-you-need-know-e13f2df512e2
